### ISSUE TITLE
in game_core.cpp, optimize reverse_points

### ISSUE THREAD

**Issue by p0licat** [nikitautiu/table#5]
24 elements in points, maybe use swaps instead of create&copy

**Comment by nikitautiu** [comment]
tu te auzi ce zici?... 24 de elemente

**Comment by p0licat** [comment]
trebuie sa fie perfect

**Comment by p0licat** [comment]
si asa nu am ce face

**Comment by nikitautiu** [comment]
O pula, optimizari premature. Totusi daca o implementezi, as zice sa faci o functie externa
Reduce coupling-ul

**Comment by nikitautiu** [comment]
Apropo, vrei tu se te ocupi de asta?

**Comment by p0licat** [comment]
da pentru mine am pus, am schimbat assignee

**Comment by nikitautiu** [comment]
ok

**Comment by nikitautiu** [comment]
Apropo, cand inchizi un issue, pune un link la commit-ul in care l-ai reparat ca sa se vada

**Comment by p0licat** [comment]
59d3a44e99e21ecd7c190e7f938f649591563fde

FIXED
